/*
 Generates public/config.js from environment variables.
 Usage (local):
   BREWLUXE_BACKEND_URL="https://your-backend.onrender.com" node scripts/generate-config.js
 On PowerShell:
   $env:BREWLUXE_BACKEND_URL = 'https://your-backend.onrender.com'; node .\scripts\generate-config.js

 The script looks for the following env vars (in order):
 - BREWLUXE_BACKEND_URL
 - NEXT_PUBLIC_BREWLUXE_BACKEND_URL
 - VERCEL_ENV_BREWLUXE_BACKEND_URL (optional)

 It writes: public/config.js with window.APP_CONFIG = { API_BASE_URL: 'https://.../api' } ;
 If no env var is present the script will use a production default placeholder and print a warning.
*/

const fs = require('fs');
const path = require('path');

function normalize(url) {
  if (!url) return null;
  let s = String(url).trim();
  // remove trailing slashes
  s = s.replace(/\/+$/g, '');
  // if doesn't end with /api append it
  if (!/\/api$/i.test(s)) s = s + '/api';
  return s;
}

const envCandidates = [
  process.env.BREWLUXE_BACKEND_URL,
  process.env.NEXT_PUBLIC_BREWLUXE_BACKEND_URL,
  process.env.VERCEL_ENV_BREWLUXE_BACKEND_URL
];

let apiBase = null;
for (const v of envCandidates) {
  if (v && v.toString().trim()) {
    apiBase = normalize(v);
    break;
  }
}

if (!apiBase) {
  // Production default - change this to your real backend if you want a no-config fallback
  apiBase = 'https://brewluxe-backend.onrender.com/api';
  console.warn('[generate-config] No BREWLUXE_BACKEND_URL found in env. Using production default:', apiBase);
}

const outDir = path.resolve(__dirname, '..', 'public');
const outFile = path.join(outDir, 'config.js');

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const content = `// Auto-generated by scripts/generate-config.js\nwindow.APP_CONFIG = { API_BASE_URL: '${apiBase}' };\n`;

fs.writeFileSync(outFile, content, { encoding: 'utf8' });
console.log('[generate-config] Wrote', outFile);
console.log('[generate-config] API_BASE_URL =', apiBase);

process.exit(0);
